import "layout.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Sidebar from "./components/layout/Sidebar";
import ExcludeModalContext from "./components/alunos/ExcludeModalContext";
import ExcludeAlunoModal from "./components/alunos/ExcludeAlunoModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid-layout h-screen`}
      >
        <ExcludeModalContext>
          <ExcludeAlunoModal />

          <Header />

          <Sidebar />

          <main className="overflow-auto p-7 bg-light-grey">{children}</main>
        </ExcludeModalContext>
      </body>
    </html>
  );
}
